version: "2"

services:
  guard-postgres:
    image: postgres
    environment:
      POSTGRES_USER: guard
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
