[package]
name = "guard-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guard-grpc = { path = "../guard-grpc" }
guard-postgres = { path = "../guard-postgres" }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6.2"

[[bin]]
name = "guard-client"
path = "src/client.rs"
